if(EXISTS "/home/daniel/projects/kamping/t/tests/test_mpi_function_wrapper_helpers[1]_tests.cmake")
  include("/home/daniel/projects/kamping/t/tests/test_mpi_function_wrapper_helpers[1]_tests.cmake")
else()
  add_test(test_mpi_function_wrapper_helpers_NOT_BUILT test_mpi_function_wrapper_helpers_NOT_BUILT)
endif()
