#!/bin/sh

# Go over all files changed by this merge 
# https://stackoverflow.com/questions/4877306/list-changed-files-in-git-post-merge-hook
git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD |
	while read changed_file; do
		if [[ "$changed_file" == ".githooks/"* ]]; then
			echo "[KaMPI.ng] Updated git hook: '$changed_file': run .githooks/install.sh for the changes to become active!"
		fi
	done
