#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
     if [ "$remote_ref" = "refs/heads/add-hooks" ]; then
        echo "Pushing to branch \"add-hooks\" is forbidden"
        exit 1
     fi
done

exit 0

