var annotated_dup =
[
    [ "kamping", null, [
      [ "internal", "namespacekamping_1_1internal.html", [
        [ "all_unique", "structkamping_1_1internal_1_1all__unique.html", null ],
        [ "all_unique< std::tuple< T, Ts... > >", "structkamping_1_1internal_1_1all__unique_3_01std_1_1tuple_3_01T_00_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "AllocNewDataBufferBuilder", "structkamping_1_1internal_1_1AllocNewDataBufferBuilder.html", "structkamping_1_1internal_1_1AllocNewDataBufferBuilder" ],
        [ "any_tag_t", "structkamping_1_1internal_1_1any__tag__t.html", null ],
        [ "buffered_mode_t", "structkamping_1_1internal_1_1buffered__mode__t.html", null ],
        [ "CallableWrapper", "structkamping_1_1internal_1_1CallableWrapper.html", "structkamping_1_1internal_1_1CallableWrapper" ],
        [ "CopyMoveEnabler", "classkamping_1_1internal_1_1CopyMoveEnabler.html", "classkamping_1_1internal_1_1CopyMoveEnabler" ],
        [ "CopyMoveEnabler< true >", "classkamping_1_1internal_1_1CopyMoveEnabler_3_01true_01_4.html", "classkamping_1_1internal_1_1CopyMoveEnabler_3_01true_01_4" ],
        [ "DataBuffer", "classkamping_1_1internal_1_1DataBuffer.html", "classkamping_1_1internal_1_1DataBuffer" ],
        [ "DataBufferBuilder", "structkamping_1_1internal_1_1DataBufferBuilder.html", "structkamping_1_1internal_1_1DataBufferBuilder" ],
        [ "default_value_type_tag", "structkamping_1_1internal_1_1default__value__type__tag.html", null ],
        [ "DiscardSerializationBuffers", "structkamping_1_1internal_1_1DiscardSerializationBuffers.html", "structkamping_1_1internal_1_1DiscardSerializationBuffers" ],
        [ "EmptyDataBuffer", "classkamping_1_1internal_1_1EmptyDataBuffer.html", "classkamping_1_1internal_1_1EmptyDataBuffer" ],
        [ "Extractable", "classkamping_1_1internal_1_1Extractable.html", "classkamping_1_1internal_1_1Extractable" ],
        [ "FilterOut", "structkamping_1_1internal_1_1FilterOut.html", null ],
        [ "FilterOut< Predicate >", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_01_4.html", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_01_4" ],
        [ "FilterOut< Predicate, Head, Tail... >", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_00_01Head_00_01Tail_8_8_8_01_4.html", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_00_01Head_00_01Tail_8_8_8_01_4" ],
        [ "FilterOut< Predicate, std::tuple< Types... > >", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_00_01std_1_1tuple_3_01Types_8_8_8_01_4_01_4.html", "structkamping_1_1internal_1_1FilterOut_3_01Predicate_00_01std_1_1tuple_3_01Types_8_8_8_01_4_01_4" ],
        [ "FlatContainer", "structkamping_1_1internal_1_1FlatContainer.html", null ],
        [ "FlatContainer< T, std::enable_if_t< is_nested_send_buffer_v< T > > >", "structkamping_1_1internal_1_1FlatContainer_3_01T_00_01std_1_1enable__if__t_3_01is__nested__send__buffer__v_3_01T_01_4_01_4_01_4.html", "structkamping_1_1internal_1_1FlatContainer_3_01T_00_01std_1_1enable__if__t_3_01is__nested__send__buffer__v_3_01T_01_4_01_4_01_4" ],
        [ "FlatContainer< T, std::enable_if_t< is_sparse_send_buffer_v< T > > >", "structkamping_1_1internal_1_1FlatContainer_3_01T_00_01std_1_1enable__if__t_3_01is__sparse__send__buffer__v_3_01T_01_4_01_4_01_4.html", "structkamping_1_1internal_1_1FlatContainer_3_01T_00_01std_1_1enable__if__t_3_01is__sparse__send__buffer__v_3_01T_01_4_01_4_01_4" ],
        [ "GenericDataBuffer", "classkamping_1_1internal_1_1GenericDataBuffer.html", "classkamping_1_1internal_1_1GenericDataBuffer" ],
        [ "has_data_member", "structkamping_1_1internal_1_1has__data__member.html", null ],
        [ "has_data_member< T, std::void_t< decltype(std::declval< T >().data())> >", "structkamping_1_1internal_1_1has__data__member_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dfe1346dc82617c01fb5c64ff94e93db8.html", null ],
        [ "has_no_unused_parameters", "structkamping_1_1internal_1_1has__no__unused__parameters.html", "structkamping_1_1internal_1_1has__no__unused__parameters" ],
        [ "has_parameter_helper", "structkamping_1_1internal_1_1has__parameter__helper.html", null ],
        [ "ignore_t", "structkamping_1_1internal_1_1ignore__t.html", null ],
        [ "is_specialization", "structkamping_1_1internal_1_1is__specialization.html", null ],
        [ "is_specialization< Template< Args... >, Template >", "structkamping_1_1internal_1_1is__specialization_3_01Template_3_01Args_8_8_8_01_4_00_01Template_01_4.html", null ],
        [ "is_std_array", "structkamping_1_1internal_1_1is__std__array.html", null ],
        [ "is_std_array< std::array< T, N > >", "structkamping_1_1internal_1_1is__std__array_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", "structkamping_1_1internal_1_1is__std__array_3_01std_1_1array_3_01T_00_01N_01_4_01_4" ],
        [ "is_std_pair", "structkamping_1_1internal_1_1is__std__pair.html", null ],
        [ "is_std_pair< std::pair< T1, T2 > >", "structkamping_1_1internal_1_1is__std__pair_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "is_std_tuple", "structkamping_1_1internal_1_1is__std__tuple.html", null ],
        [ "is_std_tuple< std::tuple< Ts... > >", "structkamping_1_1internal_1_1is__std__tuple_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "logical_xor_impl", "structkamping_1_1internal_1_1logical__xor__impl.html", "structkamping_1_1internal_1_1logical__xor__impl" ],
        [ "logical_xor_impl< void >", "structkamping_1_1internal_1_1logical__xor__impl_3_01void_01_4.html", "structkamping_1_1internal_1_1logical__xor__impl_3_01void_01_4" ],
        [ "max_impl", "structkamping_1_1internal_1_1max__impl.html", "structkamping_1_1internal_1_1max__impl" ],
        [ "max_impl< void >", "structkamping_1_1internal_1_1max__impl_3_01void_01_4.html", "structkamping_1_1internal_1_1max__impl_3_01void_01_4" ],
        [ "min_impl", "structkamping_1_1internal_1_1min__impl.html", "structkamping_1_1internal_1_1min__impl" ],
        [ "min_impl< void >", "structkamping_1_1internal_1_1min__impl_3_01void_01_4.html", "structkamping_1_1internal_1_1min__impl_3_01void_01_4" ],
        [ "mpi_operation_traits", "structkamping_1_1internal_1_1mpi__operation__traits.html", "structkamping_1_1internal_1_1mpi__operation__traits" ],
        [ "OperationBuilder", "classkamping_1_1internal_1_1OperationBuilder.html", "classkamping_1_1internal_1_1OperationBuilder" ],
        [ "parameter_type_to_integral_constant", "structkamping_1_1internal_1_1parameter__type__to__integral__constant.html", "structkamping_1_1internal_1_1parameter__type__to__integral__constant" ],
        [ "parameter_types_to_integral_constants", "structkamping_1_1internal_1_1parameter__types__to__integral__constants.html", "structkamping_1_1internal_1_1parameter__types__to__integral__constants" ],
        [ "parameters_to_integral_constant", "structkamping_1_1internal_1_1parameters__to__integral__constant.html", "structkamping_1_1internal_1_1parameters__to__integral__constant" ],
        [ "ParameterTypeEntry", "structkamping_1_1internal_1_1ParameterTypeEntry.html", "structkamping_1_1internal_1_1ParameterTypeEntry" ],
        [ "ParameterTypeUnwrapping", "structkamping_1_1internal_1_1ParameterTypeUnwrapping.html", "structkamping_1_1internal_1_1ParameterTypeUnwrapping" ],
        [ "ParameterTypeUnwrapping< std::integral_constant< T, v > >", "structkamping_1_1internal_1_1ParameterTypeUnwrapping_3_01std_1_1integral__constant_3_01T_00_01v_01_4_01_4.html", "structkamping_1_1internal_1_1ParameterTypeUnwrapping_3_01std_1_1integral__constant_3_01T_00_01v_01_4_01_4" ],
        [ "PredicateForResultObject", "structkamping_1_1internal_1_1PredicateForResultObject.html", "structkamping_1_1internal_1_1PredicateForResultObject" ],
        [ "PrependParameterType", "structkamping_1_1internal_1_1PrependParameterType.html", "structkamping_1_1internal_1_1PrependParameterType" ],
        [ "PrependType", "structkamping_1_1internal_1_1PrependType.html", null ],
        [ "PrependType< Head, std::tuple< Tail... > >", "structkamping_1_1internal_1_1PrependType_3_01Head_00_01std_1_1tuple_3_01Tail_8_8_8_01_4_01_4.html", "structkamping_1_1internal_1_1PrependType_3_01Head_00_01std_1_1tuple_3_01Tail_8_8_8_01_4_01_4" ],
        [ "rank_any_t", "structkamping_1_1internal_1_1rank__any__t.html", null ],
        [ "rank_null_t", "structkamping_1_1internal_1_1rank__null__t.html", null ],
        [ "RankDataBuffer", "classkamping_1_1internal_1_1RankDataBuffer.html", null ],
        [ "RankDataBuffer< RankType::any, type >", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1any_00_01type_01_4.html", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1any_00_01type_01_4" ],
        [ "RankDataBuffer< RankType::null, type >", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1null_00_01type_01_4.html", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1null_00_01type_01_4" ],
        [ "RankDataBuffer< RankType::value, type >", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1value_00_01type_01_4.html", "classkamping_1_1internal_1_1RankDataBuffer_3_01RankType_1_1value_00_01type_01_4" ],
        [ "ready_mode_t", "structkamping_1_1internal_1_1ready__mode__t.html", null ],
        [ "ReduceOperation", "classkamping_1_1internal_1_1ReduceOperation.html", "classkamping_1_1internal_1_1ReduceOperation" ],
        [ "ResultCategoryNotUsed", "structkamping_1_1internal_1_1ResultCategoryNotUsed.html", null ],
        [ "SendModeParameter", "structkamping_1_1internal_1_1SendModeParameter.html", "structkamping_1_1internal_1_1SendModeParameter" ],
        [ "serialization_support_tag", "structkamping_1_1internal_1_1serialization__support__tag.html", null ],
        [ "standard_mode_t", "structkamping_1_1internal_1_1standard__mode__t.html", null ],
        [ "synchronous_mode_t", "structkamping_1_1internal_1_1synchronous__mode__t.html", null ],
        [ "TagParam", "classkamping_1_1internal_1_1TagParam.html", null ],
        [ "TagParam< TagType::any, parameter_type_ >", "classkamping_1_1internal_1_1TagParam_3_01TagType_1_1any_00_01parameter__type___01_4.html", "classkamping_1_1internal_1_1TagParam_3_01TagType_1_1any_00_01parameter__type___01_4" ],
        [ "TagParam< TagType::value, parameter_type_ >", "classkamping_1_1internal_1_1TagParam_3_01TagType_1_1value_00_01parameter__type___01_4.html", "classkamping_1_1internal_1_1TagParam_3_01TagType_1_1value_00_01parameter__type___01_4" ],
        [ "type_list", "structkamping_1_1internal_1_1type__list.html", "structkamping_1_1internal_1_1type__list" ],
        [ "unused_tparam", "structkamping_1_1internal_1_1unused__tparam.html", null ],
        [ "UnusedRebindContainer", "structkamping_1_1internal_1_1UnusedRebindContainer.html", null ],
        [ "UserOperationPtrWrapper", "classkamping_1_1internal_1_1UserOperationPtrWrapper.html", "classkamping_1_1internal_1_1UserOperationPtrWrapper" ],
        [ "UserOperationWrapper", "classkamping_1_1internal_1_1UserOperationWrapper.html", "classkamping_1_1internal_1_1UserOperationWrapper" ],
        [ "ValueTypeWrapper", "classkamping_1_1internal_1_1ValueTypeWrapper.html", "classkamping_1_1internal_1_1ValueTypeWrapper" ],
        [ "ValueTypeWrapper< true, T >", "classkamping_1_1internal_1_1ValueTypeWrapper_3_01true_00_01T_01_4.html", "classkamping_1_1internal_1_1ValueTypeWrapper_3_01true_00_01T_01_4" ]
      ] ],
      [ "measurements", null, [
        [ "internal", null, [
          [ "CounterTreeNode", "classkamping_1_1measurements_1_1internal_1_1CounterTreeNode.html", null ],
          [ "Gather", "structkamping_1_1measurements_1_1internal_1_1Gather.html", "structkamping_1_1measurements_1_1internal_1_1Gather" ],
          [ "Max", "structkamping_1_1measurements_1_1internal_1_1Max.html", "structkamping_1_1measurements_1_1internal_1_1Max" ],
          [ "Min", "structkamping_1_1measurements_1_1internal_1_1Min.html", "structkamping_1_1measurements_1_1internal_1_1Min" ],
          [ "NodeMeasurements", "classkamping_1_1measurements_1_1internal_1_1NodeMeasurements.html", "classkamping_1_1measurements_1_1internal_1_1NodeMeasurements" ],
          [ "ScalarOrVectorPrinter", "structkamping_1_1measurements_1_1internal_1_1ScalarOrVectorPrinter.html", "structkamping_1_1measurements_1_1internal_1_1ScalarOrVectorPrinter" ],
          [ "Sum", "structkamping_1_1measurements_1_1internal_1_1Sum.html", "structkamping_1_1measurements_1_1internal_1_1Sum" ],
          [ "TimerTreeNode", "classkamping_1_1measurements_1_1internal_1_1TimerTreeNode.html", "classkamping_1_1measurements_1_1internal_1_1TimerTreeNode" ],
          [ "Tree", "structkamping_1_1measurements_1_1internal_1_1Tree.html", "structkamping_1_1measurements_1_1internal_1_1Tree" ],
          [ "TreeNode", "classkamping_1_1measurements_1_1internal_1_1TreeNode.html", "classkamping_1_1measurements_1_1internal_1_1TreeNode" ]
        ] ],
        [ "AggregatedTree", "classkamping_1_1measurements_1_1AggregatedTree.html", "classkamping_1_1measurements_1_1AggregatedTree" ],
        [ "AggregatedTreeNode", "classkamping_1_1measurements_1_1AggregatedTreeNode.html", "classkamping_1_1measurements_1_1AggregatedTreeNode" ],
        [ "Counter", "classkamping_1_1measurements_1_1Counter.html", "classkamping_1_1measurements_1_1Counter" ],
        [ "FlatPrinter", "classkamping_1_1measurements_1_1FlatPrinter.html", "classkamping_1_1measurements_1_1FlatPrinter" ],
        [ "SimpleJsonPrinter", "classkamping_1_1measurements_1_1SimpleJsonPrinter.html", "classkamping_1_1measurements_1_1SimpleJsonPrinter" ],
        [ "Timer", "classkamping_1_1measurements_1_1Timer.html", "classkamping_1_1measurements_1_1Timer" ]
      ] ],
      [ "ops", "namespacekamping_1_1ops.html", [
        [ "internal", null, [
          [ "commutative_tag", "structkamping_1_1ops_1_1internal_1_1commutative__tag.html", null ],
          [ "non_commutative_tag", "structkamping_1_1ops_1_1internal_1_1non__commutative__tag.html", null ],
          [ "undefined_commutative_tag", "structkamping_1_1ops_1_1internal_1_1undefined__commutative__tag.html", null ]
        ] ],
        [ "null", "structkamping_1_1ops_1_1null.html", null ]
      ] ],
      [ "plugin", null, [
        [ "dispatch_alltoall", null, [
          [ "internal", null, [
            [ "PredicateDispatchAlltoall", "structkamping_1_1plugin_1_1dispatch__alltoall_1_1internal_1_1PredicateDispatchAlltoall.html", "structkamping_1_1plugin_1_1dispatch__alltoall_1_1internal_1_1PredicateDispatchAlltoall" ]
          ] ]
        ] ],
        [ "grid", null, [
          [ "GridCommunicator", "classkamping_1_1plugin_1_1grid_1_1GridCommunicator.html", "classkamping_1_1plugin_1_1grid_1_1GridCommunicator" ]
        ] ],
        [ "grid_plugin_helpers", null, [
          [ "Destination", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1Destination.html", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1Destination" ],
          [ "GridPosition", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1GridPosition.html", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1GridPosition" ],
          [ "MessageEnvelope", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1MessageEnvelope.html", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1MessageEnvelope" ],
          [ "Source", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1Source.html", "structkamping_1_1plugin_1_1grid__plugin__helpers_1_1Source" ]
        ] ],
        [ "reproducible_reduce", null, [
          [ "MessageBuffer", "classkamping_1_1plugin_1_1reproducible__reduce_1_1MessageBuffer.html", "classkamping_1_1plugin_1_1reproducible__reduce_1_1MessageBuffer" ],
          [ "MessageBufferEntry", "structkamping_1_1plugin_1_1reproducible__reduce_1_1MessageBufferEntry.html", "structkamping_1_1plugin_1_1reproducible__reduce_1_1MessageBufferEntry" ],
          [ "ReproducibleCommunicator", "classkamping_1_1plugin_1_1reproducible__reduce_1_1ReproducibleCommunicator.html", "classkamping_1_1plugin_1_1reproducible__reduce_1_1ReproducibleCommunicator" ]
        ] ],
        [ "sparse_alltoall", null, [
          [ "internal", null, [
            [ "PredicateForSparseAlltoall", "structkamping_1_1plugin_1_1sparse__alltoall_1_1internal_1_1PredicateForSparseAlltoall.html", "structkamping_1_1plugin_1_1sparse__alltoall_1_1internal_1_1PredicateForSparseAlltoall" ]
          ] ],
          [ "ProbedMessage", "classkamping_1_1plugin_1_1sparse__alltoall_1_1ProbedMessage.html", "classkamping_1_1plugin_1_1sparse__alltoall_1_1ProbedMessage" ]
        ] ],
        [ "DispatchAlltoall", "classkamping_1_1plugin_1_1DispatchAlltoall.html", "classkamping_1_1plugin_1_1DispatchAlltoall" ],
        [ "GridCommunicator", "classkamping_1_1plugin_1_1GridCommunicator.html", "classkamping_1_1plugin_1_1GridCommunicator" ],
        [ "PluginBase", "structkamping_1_1plugin_1_1PluginBase.html", null ],
        [ "ReproducibleReducePlugin", "classkamping_1_1plugin_1_1ReproducibleReducePlugin.html", "classkamping_1_1plugin_1_1ReproducibleReducePlugin" ],
        [ "SampleSort", "classkamping_1_1plugin_1_1SampleSort.html", "classkamping_1_1plugin_1_1SampleSort" ],
        [ "SparseAlltoall", "classkamping_1_1plugin_1_1SparseAlltoall.html", "classkamping_1_1plugin_1_1SparseAlltoall" ],
        [ "UserLevelFailureMitigation", "classkamping_1_1plugin_1_1UserLevelFailureMitigation.html", "classkamping_1_1plugin_1_1UserLevelFailureMitigation" ]
      ] ],
      [ "AllocContainerOfT", "structkamping_1_1AllocContainerOfT.html", "structkamping_1_1AllocContainerOfT" ],
      [ "AllocNewT", "structkamping_1_1AllocNewT.html", "structkamping_1_1AllocNewT" ],
      [ "AllocNewUsingT", "structkamping_1_1AllocNewUsingT.html", "structkamping_1_1AllocNewUsingT" ],
      [ "builtin_type", "structkamping_1_1builtin__type.html", null ],
      [ "builtin_type< bool >", "structkamping_1_1builtin__type_3_01bool_01_4.html", "structkamping_1_1builtin__type_3_01bool_01_4" ],
      [ "builtin_type< char >", "structkamping_1_1builtin__type_3_01char_01_4.html", "structkamping_1_1builtin__type_3_01char_01_4" ],
      [ "builtin_type< double >", "structkamping_1_1builtin__type_3_01double_01_4.html", "structkamping_1_1builtin__type_3_01double_01_4" ],
      [ "builtin_type< float >", "structkamping_1_1builtin__type_3_01float_01_4.html", "structkamping_1_1builtin__type_3_01float_01_4" ],
      [ "builtin_type< int >", "structkamping_1_1builtin__type_3_01int_01_4.html", "structkamping_1_1builtin__type_3_01int_01_4" ],
      [ "builtin_type< kabool >", "structkamping_1_1builtin__type_3_01kabool_01_4.html", "structkamping_1_1builtin__type_3_01kabool_01_4" ],
      [ "builtin_type< long double >", "structkamping_1_1builtin__type_3_01long_01double_01_4.html", "structkamping_1_1builtin__type_3_01long_01double_01_4" ],
      [ "builtin_type< long int >", "structkamping_1_1builtin__type_3_01long_01int_01_4.html", "structkamping_1_1builtin__type_3_01long_01int_01_4" ],
      [ "builtin_type< long long int >", "structkamping_1_1builtin__type_3_01long_01long_01int_01_4.html", "structkamping_1_1builtin__type_3_01long_01long_01int_01_4" ],
      [ "builtin_type< short int >", "structkamping_1_1builtin__type_3_01short_01int_01_4.html", "structkamping_1_1builtin__type_3_01short_01int_01_4" ],
      [ "builtin_type< signed char >", "structkamping_1_1builtin__type_3_01signed_01char_01_4.html", "structkamping_1_1builtin__type_3_01signed_01char_01_4" ],
      [ "builtin_type< std::byte >", "structkamping_1_1builtin__type_3_01std_1_1byte_01_4.html", "structkamping_1_1builtin__type_3_01std_1_1byte_01_4" ],
      [ "builtin_type< std::complex< double > >", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01double_01_4_01_4.html", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01double_01_4_01_4" ],
      [ "builtin_type< std::complex< float > >", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01float_01_4_01_4.html", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01float_01_4_01_4" ],
      [ "builtin_type< std::complex< long double > >", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01long_01double_01_4_01_4.html", "structkamping_1_1builtin__type_3_01std_1_1complex_3_01long_01double_01_4_01_4" ],
      [ "builtin_type< unsigned char >", "structkamping_1_1builtin__type_3_01unsigned_01char_01_4.html", "structkamping_1_1builtin__type_3_01unsigned_01char_01_4" ],
      [ "builtin_type< unsigned int >", "structkamping_1_1builtin__type_3_01unsigned_01int_01_4.html", "structkamping_1_1builtin__type_3_01unsigned_01int_01_4" ],
      [ "builtin_type< unsigned long int >", "structkamping_1_1builtin__type_3_01unsigned_01long_01int_01_4.html", "structkamping_1_1builtin__type_3_01unsigned_01long_01int_01_4" ],
      [ "builtin_type< unsigned long long int >", "structkamping_1_1builtin__type_3_01unsigned_01long_01long_01int_01_4.html", "structkamping_1_1builtin__type_3_01unsigned_01long_01long_01int_01_4" ],
      [ "builtin_type< unsigned short int >", "structkamping_1_1builtin__type_3_01unsigned_01short_01int_01_4.html", "structkamping_1_1builtin__type_3_01unsigned_01short_01int_01_4" ],
      [ "builtin_type< wchar_t >", "structkamping_1_1builtin__type_3_01wchar__t_01_4.html", "structkamping_1_1builtin__type_3_01wchar__t_01_4" ],
      [ "byte_serialized", "structkamping_1_1byte__serialized.html", null ],
      [ "CommunicationGraphLocalView", "classkamping_1_1CommunicationGraphLocalView.html", "classkamping_1_1CommunicationGraphLocalView" ],
      [ "Communicator", "classkamping_1_1Communicator.html", "classkamping_1_1Communicator" ],
      [ "contiguous_type", "structkamping_1_1contiguous__type.html", "structkamping_1_1contiguous__type" ],
      [ "DistributedCommunicationGraph", "classkamping_1_1DistributedCommunicationGraph.html", "classkamping_1_1DistributedCommunicationGraph" ],
      [ "DistributedGraphCommunicator", "classkamping_1_1DistributedGraphCommunicator.html", "classkamping_1_1DistributedGraphCommunicator" ],
      [ "Environment", "classkamping_1_1Environment.html", "classkamping_1_1Environment" ],
      [ "Group", "classkamping_1_1Group.html", "classkamping_1_1Group" ],
      [ "has_static_type", "structkamping_1_1has__static__type.html", null ],
      [ "has_static_type< T, std::void_t< decltype(mpi_type_traits< T >::data_type())> >", "structkamping_1_1has__static__type_3_01T_00_01std_1_1void__t_3_01decltype_07mpi__type__traits_3_15da6b469e2a3ba98f1fb493cab97940.html", null ],
      [ "is_contiguous_sized_range", "structkamping_1_1is__contiguous__sized__range.html", "structkamping_1_1is__contiguous__sized__range" ],
      [ "is_pair_like", "structkamping_1_1is__pair__like.html", "structkamping_1_1is__pair__like" ],
      [ "is_range", "structkamping_1_1is__range.html", "structkamping_1_1is__range" ],
      [ "kabool", "classkamping_1_1kabool.html", "classkamping_1_1kabool" ],
      [ "kamping_tag", "structkamping_1_1kamping__tag.html", null ],
      [ "mpi_type_traits", "structkamping_1_1mpi__type__traits.html", null ],
      [ "mpi_type_traits< std::pair< First, Second >, std::enable_if_t< has_static_type_v< First > &&has_static_type_v< Second > > >", "structkamping_1_1mpi__type__traits_3_01std_1_1pair_3_01First_00_01Second_01_4_00_01std_1_1enable8225356c1b4dd1afe36e838bc902e3db.html", null ],
      [ "mpi_type_traits< std::tuple< Ts... >, std::enable_if_t<(has_static_type_v< Ts > &&...)> >", "structkamping_1_1mpi__type__traits_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_00_01std_1_1enable__if__t_71629c10fd8c4629866f18448d725d4c.html", null ],
      [ "mpi_type_traits< T, std::enable_if_t<!std::is_same_v< decltype(type_dispatcher< T >()), no_matching_type > > >", "structkamping_1_1mpi__type__traits_3_01T_00_01std_1_1enable__if__t_3_9std_1_1is__same__v_3_01dec857596fd4ca43a378a39fe9cb4512794.html", "structkamping_1_1mpi__type__traits_3_01T_00_01std_1_1enable__if__t_3_9std_1_1is__same__v_3_01dec857596fd4ca43a378a39fe9cb4512794" ],
      [ "MPIAllocator", "classkamping_1_1MPIAllocator.html", "classkamping_1_1MPIAllocator" ],
      [ "MpiErrorException", "classkamping_1_1MpiErrorException.html", "classkamping_1_1MpiErrorException" ],
      [ "MPIFailureDetected", "classkamping_1_1MPIFailureDetected.html", "classkamping_1_1MPIFailureDetected" ],
      [ "MPIProcFailedError", "classkamping_1_1MPIProcFailedError.html", "classkamping_1_1MPIProcFailedError" ],
      [ "MPIProcFailedPendingError", "classkamping_1_1MPIProcFailedPendingError.html", "classkamping_1_1MPIProcFailedPendingError" ],
      [ "MPIResult", "classkamping_1_1MPIResult.html", "classkamping_1_1MPIResult" ],
      [ "MPIRevokedError", "classkamping_1_1MPIRevokedError.html", "classkamping_1_1MPIRevokedError" ],
      [ "no_matching_type", "structkamping_1_1no__matching__type.html", null ],
      [ "NonBlockingResult", "classkamping_1_1NonBlockingResult.html", "classkamping_1_1NonBlockingResult" ],
      [ "PoolAnyResult", "structkamping_1_1PoolAnyResult.html", "structkamping_1_1PoolAnyResult" ],
      [ "PooledRequest", "classkamping_1_1PooledRequest.html", "classkamping_1_1PooledRequest" ],
      [ "RankRange", "structkamping_1_1RankRange.html", "structkamping_1_1RankRange" ],
      [ "RankRanges", "classkamping_1_1RankRanges.html", "classkamping_1_1RankRanges" ],
      [ "Request", "classkamping_1_1Request.html", "classkamping_1_1Request" ],
      [ "RequestBase", "classkamping_1_1RequestBase.html", "classkamping_1_1RequestBase" ],
      [ "RequestPool", "classkamping_1_1RequestPool.html", "classkamping_1_1RequestPool" ],
      [ "ScopedDatatype", "classkamping_1_1ScopedDatatype.html", "classkamping_1_1ScopedDatatype" ],
      [ "Span", "classkamping_1_1Span.html", "classkamping_1_1Span" ],
      [ "Status", "classkamping_1_1Status.html", "classkamping_1_1Status" ],
      [ "struct_type", "structkamping_1_1struct__type.html", "structkamping_1_1struct__type" ],
      [ "TopologyCommunicator", "classkamping_1_1TopologyCommunicator.html", "classkamping_1_1TopologyCommunicator" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "tuple_element< index, kamping::MPIResult< Args... > >", "structstd_1_1tuple__element_3_01index_00_01kamping_1_1MPIResult_3_01Args_8_8_8_01_4_01_4.html", "structstd_1_1tuple__element_3_01index_00_01kamping_1_1MPIResult_3_01Args_8_8_8_01_4_01_4" ],
      [ "tuple_size< kamping::MPIResult< Args... > >", "structstd_1_1tuple__size_3_01kamping_1_1MPIResult_3_01Args_8_8_8_01_4_01_4.html", "structstd_1_1tuple__size_3_01kamping_1_1MPIResult_3_01Args_8_8_8_01_4_01_4" ]
    ] ]
];