name: Feature request
description: Request a new feature or enhancement
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have used the search function for [open](https://github.com/kamping-site/kamping/issues) **and** [closed](https://github.com/kamping-site/kamping/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same feature request.
          required: true
        - label: I will describe the problem with as much detail as possible.
          required: true
        - label: This request contains only one single feature, **not** a list of multiple (related) features. Please link related feature requests.
          required: true
  - type: input
    id: kamping-version
    attributes:
      label: KaMPIng version
      description: The release number or git hash
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem you may be having, or feature you want
      description: Give a brief explanation about the problem that may currently exist
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: Describe how your requested feature solves this problem. Try to be as specific as possible. Please not only explain what the feature does, but also how.
