find_program(CCACHE_PROGRAM ccache)
if (CCACHE_PROGRAM)
    message(STATUS "Using ccache to speed up compilation.")

    set(SUPPORTED_GENERATORS "Unix Makefiles" "Ninja" "Ninja Multi-Config")
    if (CMAKE_GENERATOR IN_LIST SUPPORTED_GENERATORS)
        set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
        set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
    else ()
        message(WARNING "${CMAKE_GENERATOR} does not support <LANG>_COMPILER_LAUNCHER.")
        # See https://crascit.com/2016/04/09/using-ccache-with-cmake/#more-410 if you absolutely want to use XCode
    endif ()
else ()
    message(WARNING "Could not find ccache in your PATH.")
endif ()
