on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    container:
      image: "ubuntu:latest"
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install git
        run: apt install git
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Hello world action step
        uses: ./.github/actions/cmake-build-action # Uses an action in the root directory
        id: cmake-build-action
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
