name: clang-format

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  format:
    name: Format
    runs-on: self-hosted
    container:
      image: "localhost:5000/kamping-ci"
    steps:
    - uses: actions/checkout@v2
      with:
    # Check out HEAD on the branch
        ref: ${{ github.head_ref }}
    # Fetch all commits in the repo
        fetch-depth: 0
    - name: install clang-format
      run: apt-get install clang-format -y
    - name: Run clang-format
      run: git-clang-format ${{ github.event.pull_request.base.sha }}
    # Commit the changes (if there are any)
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Apply clang-format changes
        branch: ${{ github.head_ref }}
