name: clang-format

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  format:
    name: Format
    runs-on: self-hosted
    container:
      image: "localhost:5000/kamping-ci"
    steps:
      # Copied from https://github.com/marketplace/actions/git-clang-format-action
      - uses: actions/checkout@v2
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
      # format the latest commit
      - uses: kevmo314/clang-format-action-1@1.0.0
        # use one of clang-format's supported styles or leave this out to use the style in your .clang-format file
        with:
          style: file
      # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
