name: clang-format Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  cpp-formatting-check:
    name: C++ Formatting Check
    runs-on: self-hosted
    container:
      image: "localhost:5000/kamping-ci"
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      uses: jidicula/clang-format-action@v4.4.0
      with:
        clang-format-version: '14'
        exclude-regex: 'extern/'
